#+TITLE: Unofficial Reactive PennyPixels

This is a starter project for React programmers working at PennyMac.

 1. [[http://pennypixels.pennymacusa.com/#navs][PennyPixels]] (Because you "should" be using it)
 1. [[http://facebook.github.io/react/][React.js]] (Because it is awesome)
 2. [[http://gaearon.github.io/react-hot-loader/][Babel Hot Loader]] (Because we automate common work)
 3. [[http://webpack.github.io/docs/webpack-dev-server.html][Webpack dev server]] (If you want live code editing)
 4. [[https://github.com/cucumber/cucumber-js][Cucumber-js to automate testing]] (Or substitute another test approach)
 5. [[https://www.gnu.org/software/make/][GNU Make]] (To document and automate useful shell commands)

To get started clone the repo, delete the .git folder and start a new program.

* Why another framework?

  There are many ways to program the browser.

  React automates away the manual task of writing imperative code to 
  update the DOM. Additionally it provides a Sythetic Event System that
  can normalizes the event behavior and implements the standarized behavior.

  The automation ensures that your user interface stays consistent over a 
  series of changes by rendering on every state change. The results are captured
  in a virtual DOM which is a JavaScript representation of DOM elements. Each
  render the before and after are compared and the user interface is automatically
  updated to reflect the changes whether it is an add, update or delete.

  Additionally, this framework adopts JavaScript 2015 which is final as of June 2015.

  Finally, the live code editing makes the experience simple and easy to develop.

* Developer Workflow

  The workflow uses [[http://gaearon.github.io/react-hot-loader/][babel-hot-loader]].

** Getting Setup

   This software needs to be installed before you can build the project.

    1. Node.js / NPM

   All other developer tools come from NPM. Install them with:

   #+BEGIN_SRC sh
     make install-prereqs
   #+END_SRC
   
   Install development and runtime dependencies with:

  #+BEGIN_SRC sh
    npm install
  #+END_SRC

** Build Project

  To run the development server:

  #+BEGIN_SRC sh
    make
  #+END_SRC

  To bundle the project:

  #+BEGIN_SRC sh
    make bundle
  #+END_SRC

  To run the tests:

  #+BEGIN_SRC sh
    make test
  #+END_SRC
  
  To lint the code:

  #+BEGIN_SRC sh
    make lint
  #+END_SRC
